# -*- coding: utf-8 -*-
"""DataSci Geospatial H.W

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gxysg71r-Y8x4kEaSP134qn0B-IefiVg
"""

# Commented out IPython magic to ensure Python compatibility.
import os
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

from shapely.geometry import Point

# %pylab inline

from google.colab import drive
drive.mount('/content/drive')

# Read shapefile
ph = gpd.read_file('/content/drive/Shareddrives/DATASCI/gadm36_PHL_shp/gadm36_PHL_1.shp')
ph.head(50)

type(ph)

ax = ph.plot(figsize=(30,20), color="w", edgecolor="dimgray")

ax.axis('off')

# Read GeoJSON file
healthsites = gpd.read_file('/content/drive/Shareddrives/DATASCI/gadm36_PHL_shp/philippines.geojson')
healthsites['amenity'].unique()

Iloilo_healthsites = gpd.sjoin(healthsites, ph[ph.NAME_1=="Iloilo"], op='within')

Iloilo_healthsites['amenity'].unique()

MetroManila_healthsites = gpd.sjoin(healthsites, ph[ph.NAME_1=="Metropolitan Manila"], op='within')

MetroManila_healthsites['amenity'].unique()

"""**ILOILO HEALTH SITES**

*ILOILO CLINICS*
"""

fig = plt.figure(figsize=(30, 20))
ax = fig.add_subplot(111)
ph[ph.NAME_1=="Iloilo"].plot(ax=ax, color='white', edgecolor='dimgray')
Iloilo_healthsites[Iloilo_healthsites.amenity=="clinic"].plot(ax=ax, column="amenity", alpha=0.35, legend=True)
ax.set_title('Clinics in Iloilo', fontsize=15)
ax.axis('off');

"""*Iloilo Dentists*


"""

fig = plt.figure(figsize=(30, 20))
ax = fig.add_subplot(111)
ph[ph.NAME_1=="Iloilo"].plot(ax=ax, color='white', edgecolor='dimgray')
Iloilo_healthsites[Iloilo_healthsites.amenity=="dentist"].plot(ax=ax, column="amenity", alpha=0.35, legend=True)
ax.set_title('Dentists in Iloilo', fontsize=15)
ax.axis('off');

"""*Iloilo Doctors*"""

fig = plt.figure(figsize=(30, 20))
ax = fig.add_subplot(111)
ph[ph.NAME_1=="Iloilo"].plot(ax=ax, color='white', edgecolor='dimgray')
Iloilo_healthsites[Iloilo_healthsites.amenity=="doctors"].plot(ax=ax, column="amenity", alpha=0.35, legend=True)
ax.set_title('Doctors in Iloilo', fontsize=15)
ax.axis('off');

"""*Iloilo hospital*"""

fig = plt.figure(figsize=(30, 20))
ax = fig.add_subplot(111)
ph[ph.NAME_1=="Iloilo"].plot(ax=ax, color='white', edgecolor='dimgray')
Iloilo_healthsites[Iloilo_healthsites.amenity=="hospital"].plot(ax=ax, column="amenity", alpha=0.35, legend=True)
ax.set_title('Hospitals in Iloilo', fontsize=15)
ax.axis('off');

"""*Iloilo Pharmacy*"""

fig = plt.figure(figsize=(30, 20))
ax = fig.add_subplot(111)
ph[ph.NAME_1=="Iloilo"].plot(ax=ax, color='white', edgecolor='dimgray')
Iloilo_healthsites[Iloilo_healthsites.amenity=="pharmacy"].plot(ax=ax, column="amenity", alpha=0.35, legend=True)
ax.set_title('Pharmacy in Iloilo', fontsize=15)
ax.axis('off');

"""*Iloilo Heatlthcare*"""

fig = plt.figure(figsize=(30, 20))
ax = fig.add_subplot(111)
ph[ph.NAME_1=="Iloilo"].plot(ax=ax, color='white', edgecolor='dimgray')
ax.set_title('Other things in Iloilo', fontsize=15)
ax.axis('off');
#Iloilo does not have health care facilites

"""*Iloilo Other*"""

fig = plt.figure(figsize=(30, 20))
ax = fig.add_subplot(111)
ph[ph.NAME_1=="Iloilo"].plot(ax=ax, color='white', edgecolor='dimgray')
Iloilo_healthsites[Iloilo_healthsites.amenity==""].plot(ax=ax, column="amenity", alpha=0.35, legend=True)
ax.set_title('Other things in Iloilo', fontsize=15)
ax.axis('off');

"""**METRO MANILA HEALTH SITES**

*Metropolitan Manila CLINICS*
"""

fig = plt.figure(figsize=(30, 20))
ax = fig.add_subplot(111)
ph[ph.NAME_1=="Metropolitan Manila"].plot(ax=ax, color='white', edgecolor='dimgray')
MetroManila_healthsites[MetroManila_healthsites.amenity=="clinic"].plot(ax=ax, column="amenity", alpha=0.35, legend=True)
ax.set_title('Clinics in Metropolitan Manila', fontsize=15)
ax.axis('off');

"""*Metropolitan Manila Dentists*


"""

fig = plt.figure(figsize=(30, 20))
ax = fig.add_subplot(111)
ph[ph.NAME_1=="Metropolitan Manila"].plot(ax=ax, color='white', edgecolor='dimgray')
MetroManila_healthsites[MetroManila_healthsites.amenity=="dentist"].plot(ax=ax, column="amenity", alpha=0.35, legend=True)
ax.set_title('Dentists in Metropolitan Manila', fontsize=15)
ax.axis('off');

"""*Metropolitan Manila Doctors*"""

fig = plt.figure(figsize=(30, 20))
ax = fig.add_subplot(111)
ph[ph.NAME_1=="Metropolitan Manila"].plot(ax=ax, color='white', edgecolor='dimgray')
MetroManila_healthsites[MetroManila_healthsites.amenity=="doctors"].plot(ax=ax, column="amenity", alpha=0.35, legend=True)
ax.set_title('Doctors in Metropolitan Manila', fontsize=15)
ax.axis('off');

"""*Metropolitan Manila hospitals*"""

fig = plt.figure(figsize=(30, 20))
ax = fig.add_subplot(111)
ph[ph.NAME_1=="Metropolitan Manila"].plot(ax=ax, color='white', edgecolor='dimgray')
MetroManila_healthsites[MetroManila_healthsites.amenity=="hospital"].plot(ax=ax, column="amenity", alpha=0.35, legend=True)
ax.set_title('Hospitals in Metropolitan Manila', fontsize=15)
ax.axis('off');

"""*Metropolitan Manila Pharmacy*"""

fig = plt.figure(figsize=(30, 20))
ax = fig.add_subplot(111)
ph[ph.NAME_1=="Metropolitan Manila"].plot(ax=ax, color='white', edgecolor='dimgray')
MetroManila_healthsites[MetroManila_healthsites.amenity=="pharmacy"].plot(ax=ax, column="amenity", alpha=0.35, legend=True)
ax.set_title('Pharmacys in Metropolitan Manila', fontsize=15)
ax.axis('off');

"""*Metropolitan Manila Heatlthcare*"""

fig = plt.figure(figsize=(30, 20))
ax = fig.add_subplot(111)
ph[ph.NAME_1=="Metropolitan Manila"].plot(ax=ax, color='white', edgecolor='dimgray')
MetroManila_healthsites[MetroManila_healthsites.amenity=="healthcare"].plot(ax=ax, column="amenity", alpha=0.35, legend=True)
ax.set_title('Healthcare in Metropolitan Manila', fontsize=15)
ax.axis('off');